language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: AEQ8e+9YDyBRpJPTVoRiekEwjKT0fDenDoANFFvsfkODUsvJLSQ+kFGBjPd7rJPj5+xLpugcmqoQdvOlsQOFPiseqktwmg94vWsFrFhKC8Jw52l2tFMFruiUjKzRXAM+ZuX3v466gTDMH44TDLWbDm3HXhTnTSVy4QqDE6IJ9BIWm/s01nU010Ey01j0XIV0u5JwLbKibYdDhLVg/+ta/rXn1rTfM+8XXRxMgHgL7CcRa/UiWjxivhBDYQwjy2+6KSLWCFEwbR/njbjmEuhTpL9Es9zjk4WIgqFgkLQ8U2ozNZJchdU6WSynhPqP4CXEFEx+3IpFWrqfl/9a56h7o30p5FxskcTguOly0Xn/q6mb70kgvbxNTK5t2A+aL7Qx1jNZzAWfWiBHWKFMyurnE2f7rmFOWMWskGpmZblcrO58hQBXJKgkzKtcd6hzkJ6VNNlegDgjVU3J+26O0zh22Nr8BigVfJYqlp0HbuYQ9SOuYqU79NIS2iA1W0s741yUFQv07SBP1lLuFh/DaaNPEtPbl/8ujGzisEXCTrqEeC6sy/gjyrWHuYoBIB2BglPIoOKxvNb6Orj7hR0C+xxE8KKFy/WNjBIVesVJkRpY63bbVCmepElbGgbyrCEc4PQn28mYVi/DOM1H0MnMXAXm3P0WPme5ZWc7v4tkpxf6mow=
  app: doneperiodserver
  on:
    repo: leesyang/donePeriod-server
  skip_cleanup: 'true'
