language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: vClPa6vb4F/RKo/Iu/MipAjO0s+Bh9jC7UuxxtEnrKjyJkb/ZeC+NxwgQ1dh4cof0uuk9ymswT7qO0GNCeOUP9Y1ZegpYdb5Yn4NlMKMpMYIXyrOjqbQtEoLSEU7xHao0V0oG5id043Rwu/4HXZ1yy0LlRJW5pkDf91TSxxsytDSlNdTe0R72GrjJIk6wAdVD7cefuCQmeYhNK3QWLoO3+Rkonsp4LaVgPYJ9zRfXn33EoLbzvNxf78kMGBVpbxT3MKH1YLmk492BUUgd1UpNjwYAM70ZtIH9MwmAMqeOyTkQTbZ6ILcC9F0ifo7lSkBsM8NlrWSNYMrOqS35Vk8iupQDRvA1B8oK3HCh28bru578LlY70TB5WDA+HIC/HIDtZMYZ7Hc7KKNGxCqjWODnuaNREqaNbWGP3xWI5WqgQBd/JfSeC+opDFTj8THQO9ICFYNEaRXrMbVc9M4MEeMNxYbZf+0kqegJroNJQI7eWS1Ig12HQQ4tSy9FbsoTKesjxfRhwBS+vyJik/zmCpiRUrFq3Z5FCOBM8RElX4bqJ6+/yV8UXMbU+xRdyt8KT84LI0GitI3qlYCXkRGJesecX6K+3G+BfgCyby1ryk+DLVmJQrN4eS0bVW4PRdYI5P2D+kcj5H4ChOSgAdT4QskO4JJZPHMx1b5imJ4EWfAgNw=
  app: donePeriod-server
  on:
    repo: leesyang/donePeriod-server
  skip_cleanup: 'true'
