language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: JGhL+WRfdAcQgBOme1XO/d9GZ+eC2SZ9FH/ymIExokKQijn86uFzhaN+0Wi+fEqhbMv3cYlRn9QQ2Y9WpPkRXt+HcXvfvVfbhANkCYGijMsI1m+qayTfWo2rvYZbXb/JEZEncQ1L1R35ZEbG12FgG07H+215LY/aMOOitdT3vRGk2vQ4+N0eg/vNhwBRGWkWJ0ai7WyDF6pbkEZf2hEhZl3REzRFvn/wqer/ZeoMQALXjJxc5MhOHng4njcpgHGqAX9Re6TeNS7ovUUkEwheArsDIfLpYr4l0Y3KtdWVUF9M0/kuZmckDCF9oxuuj3Gng+EiqJoVLhy1uxwkqMTwmesXE08PSLAVHyMvSDJ3X4m1J0KNSdxQVjrD9edrgIoSqRPkITgqLjS4qYlvdwgFpfH8jTd+5c6GXipOd2+T9TM6O8t28wZg42WnptsMFx/JGQVi1dh5BGzPwxn0IyThH8kOH7cr6neGR8t6Nmd4lnJt04JWINA8YkQ94Va7VsSGGgV3VHfdsnQPDW1KmJJwy01l4l4S9kVKCR8QnWOTTM59EiHlsEEfpPi/rneIdGdZOsURYBZwbZ94aA1RPH6nBsROvRb91wqgz6pRK7XyI0OFhGaQkb7B8FO2ava/P2SmzShoGBgy0HLV3Mom0byFajGRwxZFWEFu9/jruhl53uA=
  app: doneperiodserver
  on:
    repo: leesyang/donePeriod-server
  skip_cleanup: 'true'
