language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: RelF9/Ufy2C2GEAAue3Mye8sim6qJCZFgC4fJsNK0VWjrncVk4S0Mu9eWEh592riGWfHw+PulBfYcoaO6TsO+HzP2KTzP7pjpWuKFVkr4NSIjUILioBG9E1z6qIgkm68dGO64mlDgNji/n1BJXD3U9Wn/Vq2h0F8Mpcrkqw+RpzqERh+oS6KiCfUDXwx3bugyD7h1A50BQf9A/DF5zPZYoMbBNgPYTExhMxLCTHPGerg5fwmac+fcCpQ4/q7p6JkrLjXX9CIj3fcj7Oq+VSBCDfK/NaPhTh3GC4FJ1UKknpF44DPFTu0PZIIj+QtlVShBOoJ/2fB0VJ5DRyK6VjfjXc03RtqIvMr48v9+pPKg/k8noDTqHAb48Tz+kMbAapfd1XPLmlcs65Ef+y3xbQq7jWcYZA2h8AENYlS4A4QprJ/h90WUX60adHXUj4ZCQ8PmvgNRG3zH308c7Qmqd2n/U6HDwcpuYJv7AXQlkRhz/CeBzQXp0dzuqRVukhN1QO2CXOWflJnucMk3sKrsCmggPvyZZlNNEiHaHcdRiGUijMxQOohhxs1plHsWUv/MZR7gu9dkI7VdQ/Mpw6WCNjKcHiYA0GiPfMuEOFi8Jcua8JJ8fqoPPLm8UNLnxhnOnd0S9hFovk5KIUJJ8MX9djcVJq1lzIOdYUgypJXd6ZPoYQ=
  app: doneperiodserver
  on:
    repo: leesyang/donePeriod-server
  skip_cleanup: 'true'
