language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Mf3fK+dBleAjdMIEw8ER/ob/vZV0lUrjeYTyQhEn5ZuEVdFMKd5PlJgum0hNsVd2JkAendxdCC9CTG8V3+dW0qNaWfm/yZNtJDzfyxjNrNg6enc4yyFpuRgAHAsakJYYpS8QxRSsKYRe8fMu8WtR1ksAdY89FF5sCJqPlo5ZCnji8HE4qVWojDLB+j03Cbx35myTSuIH4jGQKRXBLMlGOzeCWCf28zGIwLivL37lQMDiFAiG7DzC3d3+kjIouUqXv64vFW5FoHKnwlcFGBXtGzyRqZXGGw9YQElgZuS/Cz4haSbuKWScfzsEv73M8Hw98Pmk5aicyN5LZVfMzhXfP7qG6ndzk9uP6HOiSSnT72s/yHb/2OiHpJXsgjWHicStimlgimBS5XfgXRdNPg9g3qTb4MTbArJWQ4zy5uzZVUDqk6MuS8Rrugd7Y96/wczOOZnlMBlNQ8hJIFOmWg6EqMbhdD9ZXtAUhKw3yzK0TL5W+Y6v1Gh1U5oODZNuQ74xn85YAx8PH8PDGf/Ch1exGu/5fZ8btHQEo3qWkUwg82X13BG+09MFqH9AMRA3EymaZDZRUQeG59mso2byGV1CW9HlEAxLtT8hOvVP2gHdRG0gk7dKFchPQJzx/MxGnYpKFvPg26dP38KjwE0nSYq28zsVjFOOnNlrXz5zIiLDA4s=
  app: vast-tor-64659
  on:
    repo: leesyang/donePeriod-server
