language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: s9HxSW3Uk+EOzDw764yJYxhouyJ4W6Cq5VRYt3XYrm+Be9N52IystKHJGTqf/369C3ax7J2kuaXLtJWBzuTF9KoKgKKnLNnGHyi2J20nAmQdu1iOyGv2X8YbLy5lyFMGVRLCm1Mur0lKjxDOOJZjC8g8dTlU0kYdUpXkjnl6eZNmfVZGl5pwsEmOPytZ6Qc9uamRDlAze9zdIqRFkFtcxLwQcqzYu4OqbSP6NzaUgW7Pvo5Ss397IDCGap5kkjoHWc1NnuhapYVn+9lQSJ1W/HdWVzZh2Kv/EZHA82BmnFdTVT7IJZzi5e2WX8WVQ26DTfBVv5nH01hu+RpznEC7bPxPT/h0LcyDCD8/0uQo42/mG/WqSgLjQmKWakSDmkaHwXp1mn1itQo+wUoPgZo6g5kNygB0pkgNlTCYEerK4+hbOWNZlhCf9doJBhaDXYvZByZx/ytkclKdXWPVcFlAt+SZLVR4xcSW0jycictJiIv2FFeLYlJ8aWPPwFDUI+LrCws+l2JLAabUnOZbdB+qSUpJmpiyrFXv3dOvc7ULhOPbU1hJkuTVFr5ZgGfdkXWfu1Aa+vIckHoEn0Xvpkqyovqyl62zqQQQEVo/UQrUw+pqG6Juk5u1b4e/63957D+u+vN/nlUei308yOlmhNjs5mhygkqxxYA6oQWoyE+uU1c=
  app: donePeriod-server
  on:
    repo: leesyang/donePeriod-server
